_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.9.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.10
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
autoaugment:
    value: true
batch_size:
    value: 256
beta1:
    value: 0.9
beta2:
    value: 0.99
checkpoint_epoch:
    value: 0
clip_grad:
    value: 0
cutmix_beta:
    value: 1
cutmix_prob:
    value: 0.5
dataset:
    value: imgnet
denominator:
    value: -2
device:
    value: cuda
drop_p:
    value: 0
epochs:
    value: 600
eval_batch_size:
    value: 512
gamma:
    value: 0.1
grid:
    value:
        - -2
        - 2
grid_max:
    value: 2
grid_min:
    value: -2
grid_type:
    value: uniform
hidden_c:
    value: 900
hidden_s:
    value: 112
hidden_size:
    value: 225
init:
    value: default
init_scale:
    value:
        - 0.11
is_cls_token:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.001
min_lr:
    value: 1e-06
model:
    value: kan_mixer
momentum:
    value: 0.9
nesterov:
    value: true
num_grids:
    value: 8
num_layers:
    value: 9
num_workers:
    value: 12
off_act:
    value: false
off_nesterov:
    value: false
optimizer:
    value: adam
patch_size:
    value: 16
scheduler:
    value: cosine
seed:
    value: 3407
skip_min:
    value: 1
u_epoch:
    value: 1
u_norm:
    value: 0
use_ffcv:
    value: 0
w_norm:
    value: 0
warmup_epoch:
    value: 5
weight_decay:
    value: 0
