_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.9.10
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.10
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
autoaugment:
    value: true
batch_size:
    value: 256
beta1:
    value: 0.9
beta2:
    value: 0.99
checkpoint_epoch:
    value: 0
clip_grad:
    value: 0
cutmix_beta:
    value: 1
cutmix_prob:
    value: 0.5
dataset:
    value: imgnet
device:
    value: cuda
drop_p:
    value: 0
epochs:
    value: 600
eval_batch_size:
    value: 256
gamma:
    value: 0.1
hidden_c:
    value: 512
hidden_s:
    value: 64
hidden_size:
    value: 128
init:
    value: uniform
init_scale:
    value: 0.0002
is_cls_token:
    value: false
label_smoothing:
    value: 0.1
lr:
    value: 0.001
mean:
    value:
        - 0.485
        - 0.456
        - 0.406
min_lr:
    value: 1e-06
model:
    value: kan_mixer
model_configs:
    value: kan_mixer_imgnet_adam_cosine_0.001_PS8_HSize128_HC512_HS64_NL4_SM1.0_PARAMS8688676_inituniform_scale_0.0002
momentum:
    value: 0.9
nesterov:
    value: true
num_classes:
    value: 100
num_grids:
    value: 8
num_layers:
    value: 4
num_workers:
    value: 12
off_act:
    value: false
off_nesterov:
    value: false
optimizer:
    value: adam
padding:
    value: 28
patch_size:
    value: 8
scheduler:
    value: cosine
seed:
    value: 3407
size:
    value: 224
skip_min:
    value: 1
std:
    value:
        - 0.229
        - 0.224
        - 0.225
use_ffcv:
    value: 0
warmup_epoch:
    value: 5
weight_decay:
    value: 5e-05
